-- =============================================================================
-- chora-observability : 0004_analytics.sql
--
-- Subsumes the analytics learning-event aggregation tables from the retired
-- chora-analytics service (consolidated 2026-05-12 per
-- docs/architecture/m12-2-consolidation-plan-2026-05-12.md Batch 2 / M12.2.E.4).
--
-- Domain   : Observability (supporting/platform)
-- Database : chora_observability
-- Date     : 2026-05-12
--
-- chora-analytics previously held NO durable state (in-memory only). This
-- migration provisions the Postgres-backed aggregation tables that M13+ will
-- begin populating from Pub/Sub event ingestion. Tables follow the
-- multi-tenant-rls skill — every tenant-scoped row carries tenant_id and the
-- domain-level RLS policy from 0002_schema_lockdown.sql composes here.
--
-- All counts stored as BIGINT to avoid overflow on long-running tenants. UUIDs
-- use UUIDv7 (per .claude/rules/ddd-enforcement.md invariant #7) generated by
-- the analytics slice in Go before insertion (no gen_random_uuid() default —
-- UUIDv7 is application-generated for ordering monotonicity).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- analytics_event_buckets — per-(tenant, period, period_start) event counters
--
-- Replaces the in-memory event_aggregator.Aggregator buckets. The
-- (domain, aggregate, event_type) triple is normalised across the 12-DB
-- topology; counts are read-only projections aggregated from Pub/Sub events.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_event_buckets (
    bucket_id         UUID         PRIMARY KEY,
    tenant_id         UUID         NOT NULL,
    period            VARCHAR(8)   NOT NULL CHECK (period IN ('hour', 'day', 'week', 'month')),
    period_start      TIMESTAMPTZ  NOT NULL,
    event_domain      VARCHAR(32)  NOT NULL,
    event_aggregate   VARCHAR(64)  NOT NULL,
    event_type        VARCHAR(64)  NOT NULL,
    count             BIGINT       NOT NULL DEFAULT 0 CHECK (count >= 0),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- One row per (tenant, period, period_start, triple). Upserted on each
    -- event ingest; idempotency enforced upstream via analytics_event_seen.
    UNIQUE (tenant_id, period, period_start, event_domain, event_aggregate, event_type)
);

CREATE INDEX IF NOT EXISTS idx_aeb_tenant_period
    ON analytics_event_buckets (tenant_id, period, period_start DESC);

CREATE INDEX IF NOT EXISTS idx_aeb_tenant_domain
    ON analytics_event_buckets (tenant_id, event_domain, event_aggregate);

-- -----------------------------------------------------------------------------
-- analytics_event_seen — idempotency log (Pub/Sub at-least-once guard)
--
-- One row per ingested envelope idempotency_key, scoped by tenant. Used to
-- short-circuit double-counting under Pub/Sub redelivery (which is the norm).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_event_seen (
    tenant_id         UUID         NOT NULL,
    idempotency_key   VARCHAR(128) NOT NULL,
    observed_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tenant_id, idempotency_key)
);

-- -----------------------------------------------------------------------------
-- analytics_cohorts — tenant-scoped cohort aggregate root
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_cohorts (
    cohort_id    UUID         PRIMARY KEY,
    tenant_id    UUID         NOT NULL,
    name         VARCHAR(255) NOT NULL,
    criteria     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ  NULL  -- soft delete per ddd-enforcement #5
);

CREATE INDEX IF NOT EXISTS idx_cohorts_tenant
    ON analytics_cohorts (tenant_id) WHERE deleted_at IS NULL;

-- -----------------------------------------------------------------------------
-- analytics_cohort_members — (cohort, gcid, joined_at) tuples
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_cohort_members (
    cohort_id    UUID         NOT NULL REFERENCES analytics_cohorts (cohort_id) ON DELETE CASCADE,
    gcid         UUID         NOT NULL,
    tenant_id    UUID         NOT NULL,  -- denormalised for RLS efficiency
    joined_at    TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (cohort_id, gcid)
);

CREATE INDEX IF NOT EXISTS idx_cohort_members_tenant
    ON analytics_cohort_members (tenant_id, cohort_id);

-- -----------------------------------------------------------------------------
-- RLS — every analytics table is tenant-scoped per multi-tenant-rls skill.
-- The session-level tenant context (app.current_tenant_id) is set by the
-- service via SET LOCAL on every transaction.
-- -----------------------------------------------------------------------------
ALTER TABLE analytics_event_buckets   ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_event_seen      ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_cohorts         ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_cohort_members  ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_analytics_event_buckets
    ON analytics_event_buckets
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

CREATE POLICY tenant_isolation_analytics_event_seen
    ON analytics_event_seen
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

CREATE POLICY tenant_isolation_analytics_cohorts
    ON analytics_cohorts
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

CREATE POLICY tenant_isolation_analytics_cohort_members
    ON analytics_cohort_members
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

COMMIT;
